### ISSUE TITLE
libdbus-c++

### ISSUE THREAD

**Issue by jeremiah** [Pelagicore/softwarecontainer#407]
Building SoftwareContainer on the Raspberrypi3 I cannot install all the dependencies. There is no libdbus-c++-1-0v5 (though there is a libdbus-c++-1-0). Where can I find this library?

$ uname -a
> Linux raspberrypi3 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux

$ cat /etc/debian_version 
> 8.0

**Comment by tobsan** [comment]
Hey @jeremiah. Which version of SoftwareContainer are you building? There should be no dependencies on libdbus-c++ at all, since we've switched to using the glibmm dbus bindings.

> I'm building the latest version from master.

Are you building this in yocto or on your rPi?

> Directly on the Pi! :-)

**Comment by tobsan** [comment]
I just noticed that there are some leftovers from libdbus-c++ in some pc files etc. Working on removing them right now, but there are no dependencies to it in CMake since a while back.

**Comment by tobsan** [comment]
As of #410 this is fixed.
